- chrome/content/lightning-item-iframe.js
Fix little typo in item dialog javascript which bugged the save of content for newly created tasks.
> lightning-item-iframe.js: fix content saving for new items

- chrome/content/attachments-view.js
I've noticed that the context menu on right clik on attachment list is not correctly overlayed.
Thus to overlay the XUL context popup on attachment list we now use the setAttribute DOM function.
As we don't modify attributes like "value" or "selected", we can use this function without any issue about modifying default value instead of real value.
> attachments-view.js: use setAttribute DOM API

- install.rdf
- locale/exchangecalendar/it-IT/attachments-view.dtd
- locale/exchangecalendar/it-IT/browseFolder.dtd
- locale/exchangecalendar/it-IT/calExchangeCalendar.properties
- locale/exchangecalendar/it-IT/calendar-calendars-list.dtd
- locale/exchangecalendar/it-IT/calendar-summary-dialog.dtd
- locale/exchangecalendar/it-IT/delegate-calendar-dialog.dtd
- locale/exchangecalendar/it-IT/delegate-folder.dtd
- locale/exchangecalendar/it-IT/ecCalendarCreation.dtd
- locale/exchangecalendar/it-IT/exchangeCloneSettings.dtd
- locale/exchangecalendar/it-IT/exchangeReminderDialog.dtd
- locale/exchangecalendar/it-IT/exchangeSettings.dtd
- locale/exchangecalendar/it-IT/exchangeSettingsOverlay.dtd
- locale/exchangecalendar/it-IT/extra-priority.dtd
- locale/exchangecalendar/it-IT/invitationResponse.dtd
- locale/exchangecalendar/it-IT/inviteStyle.dtd
- locale/exchangecalendar/it-IT/lightning-item-iframe.dtd
- locale/exchangecalendar/it-IT/manageEWSAccounts.dtd
- locale/exchangecalendar/it-IT/messenger_task_delegation.dtd
- locale/exchangecalendar/it-IT/oofSettings.dtd
- locale/exchangecalendar/it-IT/preInvitationResponse.dtd
- locale/exchangecalendar/it-IT/preferences.dtd
- locale/exchangecalendar/it-IT/rtews.dtd
- locale/exchangecalendar/it-IT/rtews.properties
- locale/exchangecalendar/it-IT/selectEWSUrl.dtd
- locale/exchangecalendar/it-IT/sendUpdateTo.dtd
- locale/exchangecalendar/it-IT/sharedCalendarParser.dtd
- locale/exchangecalendar/it-IT/timezonePreference.dtd
This pull request adds the Italian localization to the addon.
Note: the text `Dutch, French, English, German, Swedish, Japanese and Italian localizations.` in `install.rdf` needs to be updated in the Dutch/French/German/Swedish/Japanese addon descriptions in the same file.
> Translate the addon to Italian

- chrome/content/exchWebServiceEditor.xml
- chrome/content/lightning-item-iframe.js
- chrome/content/lightning-item-iframe.xul
This series of patch makes a main cleanup of the HTML content editor:
- enable back correctly buttons to set color font and background font
- synchronize constructor and destructor of the XBL widget
- makes again reliable the XBL widget initialization (Fixes #28 )
It includes commits from #30 , so it will fixes #29 too.
That was needed as the fix for the initialization modified same files than the one for event contents.
> Fix HTML content editor

- components/ecExchangeRequest.js
Explicitly specifying utf-8 in the request header seems to be needed for proper handling of foreign characters when POSTing to (at least) Exchange Server 2007. Without it, any non-ascii characters are converted to "??".
> Specify utf-8 in request header

- interfaces/exchangeCalendar/mivExchangeCalendar.js
mivExchangeCalendar.js: getItemsFromMemoryCache: fix looking for items in memory cache
The code before were using simple day index to go through start and end of the
range. Furthermore, it didn't managed that range were given in local timezone
and memory cache is in UTC.
This fix use Lightning tools to go through range and it converts local timezone
to UTC, so the cache is correctly read.
Fixes #67
> Fix timezone display part 3 / 5

- locale/exchangecalendar/tr/attachments-view.dtd
- locale/exchangecalendar/tr/browseFolder.dtd
- locale/exchangecalendar/tr/calendar-calendars-list.dtd
- locale/exchangecalendar/tr/delegate-calendar-dialog.dtd
- locale/exchangecalendar/tr/ecCalendarCreation.dtd
- locale/exchangecalendar/tr/exchangeCloneSettings.dtd
- locale/exchangecalendar/tr/exchangeReminderDialog.dtd
- locale/exchangecalendar/tr/exchangeSettings.dtd
- locale/exchangecalendar/tr/exchangeSettingsOverlay.dtd
- locale/exchangecalendar/tr/extra-priority.dtd
- locale/exchangecalendar/tr/invitationResponse.dtd
- locale/exchangecalendar/tr/inviteStyle.dtd
- locale/exchangecalendar/tr/lightning-item-iframe.dtd
- locale/exchangecalendar/tr/manageEWSAccounts.dtd
- locale/exchangecalendar/tr/messenger_task_delegation.dtd
- locale/exchangecalendar/tr/oofSettings.dtd
- locale/exchangecalendar/tr/preInvitationResponse.dtd
- locale/exchangecalendar/tr/preferences.dtd
- locale/exchangecalendar/tr/selectEWSUrl.dtd
- locale/exchangecalendar/tr/sendUpdateTo.dtd
- locale/exchangecalendar/tr/sharedCalendarParser.dtd
DTD files contained characters “ and ” instead of the double quotes (").
It seems to not be valid for DTD files, as Transifex has been stuck due to these characters.
This pull request has removed them automatically with a grep & sed command.
> Enable transifex part 2 on 3

- .tx/config
- locale/exchangecalendar/tr/attachments-view.dtd
- locale/exchangecalendar/tr/browseFolder.dtd
- locale/exchangecalendar/tr/calendar-calendars-list.dtd
- locale/exchangecalendar/tr/delegate-calendar-dialog.dtd
- locale/exchangecalendar/tr/ecCalendarCreation.dtd
- locale/exchangecalendar/tr/exchangeCloneSettings.dtd
- locale/exchangecalendar/tr/exchangeReminderDialog.dtd
- locale/exchangecalendar/tr/exchangeSettings.dtd
- locale/exchangecalendar/tr/exchangeSettingsOverlay.dtd
- locale/exchangecalendar/tr/extra-priority.dtd
- locale/exchangecalendar/tr/invitationResponse.dtd
- locale/exchangecalendar/tr/inviteStyle.dtd
- locale/exchangecalendar/tr/lightning-item-iframe.dtd
- locale/exchangecalendar/tr/manageEWSAccounts.dtd
- locale/exchangecalendar/tr/messenger_task_delegation.dtd
- locale/exchangecalendar/tr/oofSettings.dtd
- locale/exchangecalendar/tr/preInvitationResponse.dtd
- locale/exchangecalendar/tr/preferences.dtd
- locale/exchangecalendar/tr/selectEWSUrl.dtd
- locale/exchangecalendar/tr/sendUpdateTo.dtd
- locale/exchangecalendar/tr/sharedCalendarParser.dtd
Finally this part init and configures the Transifex project inside Github.
The Transifex client is simply configured with file `.tx/configure`.
This file has been semi-autogenerated with commands `find` (to look for files to translate) and `tx` (the transifex client).
Update: add review parts:
* Stuff to fix double quotes: https://github.com/ExchangeCalendar/exchangecalendar/pull/89/commits/68682df80c603807bb4aa9410903a068fbb8837c 
* Stuff to configure Transifex: https://github.com/ExchangeCalendar/exchangecalendar/pull/89/files/68682df80c603807bb4aa9410903a068fbb8837c..d2a649c164da0cd784a4f5e1e265433c39f347dd
> Enable transifex part 3 on 3

- install.rdf
Remove long descriptions as [Mozilla documentation](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests)
says that it should be one short line.
Add a link to the GitHub repo to give more complete informations to user.
Note: this PR comes from a split of #70 with more tested install.rdf file.
> install.rdf: update with ExchangeCalendar informations

- chrome.manifest
- interfaces/exchangeAddressBook/exchangeAddressBook.manifest
Last commit for Transifex has been made too fast and it has broken some localisations like fr-FR by applying "find and replace".
To set the default language, I've setted the `en` locale first, as my broken `fr-FR` build had `nl` localisations.
> l10n: fix last commit about Transifex and set en as default locale

- Makefile
- install.rdf
This patch updates the beautify-javascript Makefile target to add new line at end of files automatically.
The beautify-xml Makefile target is also updated to not wrap by default RDF files.
That's especially needed for the `install.rdf` file which needs to keep the description on one line as Thunderbird displays all spaces and new lines in add-on description.
> Update beautify targets to add newline at end of Javascript files and to not wrap install.rdf

- components/ecExchangeRequest.js
The observer created on 'http-on-modify-request' was showing password in logs
even if the user asked to not show password in logs.
This patch automatically replaces password by `***` in the URIs before logging them.
Fix #100
> ecExchangeRequest.js: hide password in logs.

- chrome/content/otherPreferences.xul
- defaults/preferences/debug.js
- locale/exchangecalendar/en/preferences.dtd
- locale/exchangecalendar/en_US/preferences.dtd
It disable all preferences modification made by the default/preferences/debug.pref.js.
I didn't remove the file directly, because I wanted to keep information about which configs orignal others have found interesting to modify.
As suggested in the Ericsson/exchangecalendar#506 pull request, I've added a preference choice to enable/disable the Thunderbird global index:
I've looked at the Thunderbird preference to add an information directly in the "Thunderbird Prefrences dialog > Advanced > Advanced Configuration". But I failed to add the information there, because I wasn't able to do all the path through ids to add an element after the global indexer checkbox.
PS: Please note you have to try this fix in a en-US Thunderbird installation, because we need to create labels in all languages …
> Disable debug preferences

- .gitignore
- Makefile
- defaults/preferences/.gitignore
- defaults/preferences/update.js
- install.rdf.template
Address a few platform differences such as `sed -i` option and omitting the current directory if it is the only path argument to `find`.
Also, make builds repeatable and not touch source-controlled files, and .gitignore build artifacts.
> Fix builds on macOS

- Makefile
As reported in #145 , this PR disable automatic commits for the `release` target.
> Makefile: release target does not update translations any more

- common/content/priority-display.js
It fixes some errors appearing in console about for `priority-display.js` line 40.
The fix just does correctly use of [nsIPrefService](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefService) and [nsIPrefBranch](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefBranch) interfaces from Mozilla.
> fix priority-display.js to get correctly preferences from Thunderbird branches

- calendar/content/messenger_task_delegation.js
- calendar/interface/exchangeCalendar/mivExchangeCalendar.js
- common/content/exchangeSettingsOverlay.js
- common/content/manageEWSAccounts.js
- common/content/oofSettings.js
With code tree reorganization, default namespace is now exchangecommon.
The file calExchangeCalendar.properties is used inside common parts like
exchange settings and out of office settings.
It's also used in calendar part to give user some information about
current calendar synchronization jobs.
I've decided to just modify JavaScript code to use the new namespace
instead of moving the properties file, because:
- It only required to modify 48 lines of code
- If I've chosen to move the file to the exchangecalendar namespace
I would done a dependency from the common part to the calendar part.
- To split the file in two parts, it would require too lot of work to
synchronize the split between all translated files.
Closes #152
> Strings from calExchangeCalendar.properties are located in the exchangecommon namespace

- common/interface/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js
A typo introduced with PR #155 , sorry.
> mivExchangeAuthPrompt2: fix syntax typo

- common/interface/global/mivFunctions.js
I took the opportunity to prefix with `ExchangeCalendar` instead of `1st-setup:` too.
Now, logs, looks like:
> ExchangeCalendar [2018-02-05T22:55:28.158Z]: 4f792b62-b071-4e14-97f8-8ed6eb37786c:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
Closes #107
> mivFunctions.js: LOG now uses ISO format to write current time in logs (in UTC timezone)

- common/interface/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js
Before these modifications, there was an error in the
'asyncPromptAuthNotifyCallback' implementation using a not defined
`index` variable.
The unified method to getRealm try to be a little bit more compliant
with the RFC defining Basic HTTP Authentication.
> mivExchangeAuhtPrompt2: unify the way to find realm for Basic HTTP Authentication

- calendar/interface/exchangeCalendar/mivExchangeCalendar.js
- common/interface/exchangeBaseItem/mivExchangeBaseItem.js
Try to fix #203  after user report of invalid makeURL method.
I wasn't able to reproduce the bug, but Lightning has already modified their code with a patch like this one. (see bug report of Lightning inside commit message).
> replace use of obsolete makeURL by Services.io.newURI

- calendar/interface/exchangeCalendar/mivExchangeCalendar.js
- common/interface/exchangeBaseItem/mivExchangeBaseItem.js
I'm not sure if it's relevant, but I think that's really wired to use a not reserved domain to points to "somewhere" (particularly with opened to reserve root domains).
> Replace http://somewhere by http://localhost

- calendar/interface/exchangeCalendar/mivExchangeCalendar.js
- common/exchangeapi/erDeleteItem.js
As warned in JS console with this message:
> DEPRECATION WARNING: calUtils' cal.isToDo() has changed to cal.item.isToDo()
More information on the Mozilla bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1433156
Note that in the Mozilla bug report they talk about the resource `calItemUtils.jsm`.
First, I've tried to include this resource, but I got immediately a message in the console saying I had to not include this resource as it is already included by the main `calUtils.jsm` resource.
Fix #221
> cal.isToDo has to be replaced with cal.item.isToDo

- addressbook/content/addressbookOverlay.js
- addressbook/content/exchangeContactsInit.js
- addressbook/interface/exchangeAbDirFactory/exchangeAbDirFactory.js
- addressbook/interface/exchangeAbDirFactory/exchangeAbDirFactory.manifest
- addressbook/interface/exchangeAbRootDirectory/exchangeAbRootDirectory.js
- addressbook/interface/exchangeAbRootDirectory/exchangeAbRootDirectory.manifest
- addressbook/interface/exchangeAutoCompleteSearch/mivExchangeAutoCompleteSearch.js
- common/content/check4lightning.js
To be able to view again the ExchangeContact address book, we have to use lower case in the new scheme created by the extension.
To better show the scheme is specific to the ExchangeCalendar extension, I've updated it to the name `exchangecalendar-addressbook://`.
Fix #209
> exchange-contacts use a new scheme for address books

- addressbook/content/exchangeContactSettings.xul
- addressbook/locale/en/exchangeContactSettings.dtd
- common/content/exchangeSettingsOverlay.js
- common/content/exchangeSettingsOverlay.xul
- common/content/oofSettings.js
- common/locale/en/exchangeSettingsOverlay.dtd
* Add window elements to grid for vertical centering.
* Fix incorrect use of sentence dot in UI elements.
* Simplify wording.
* Make email address field scale with window.
* Remove dead code.
* Improve code formatting.
> #241 Input window usability can be improved

- common/content/exchangeCloneSettings.js
- common/content/exchangeCloneSettings.xul
- common/locale/cs_CZ/exchangeCloneSettings.dtd
- common/locale/de/exchangeCloneSettings.dtd
- common/locale/en/exchangeCloneSettings.dtd
- common/locale/en_US/exchangeCloneSettings.dtd
- common/locale/es_ES/exchangeCloneSettings.dtd
- common/locale/fr_FR/exchangeCloneSettings.dtd
- common/locale/gl/exchangeCloneSettings.dtd
- common/locale/hu/exchangeCloneSettings.dtd
- common/locale/it_IT/exchangeCloneSettings.dtd
- common/locale/ja_JP/exchangeCloneSettings.dtd
- common/locale/nl/exchangeCloneSettings.dtd
- common/locale/pl/exchangeCloneSettings.dtd
- common/locale/pt_BR/exchangeCloneSettings.dtd
- common/locale/ro/exchangeCloneSettings.dtd
- common/locale/ru/exchangeCloneSettings.dtd
- common/locale/sk/exchangeCloneSettings.dtd
- common/locale/sv/exchangeCloneSettings.dtd
- common/locale/tr/exchangeCloneSettings.dtd
* Fix label alignment.
* Improve calendar name label text.
* Improve variable declarations.
* Fix missing semicolon.
* Improve comparison operator.
> #280 Bad UI layout and label in Calendar clone window

- common/content/oofSettings.xul
Since some time the include of chrome://messenger/content/bindings.css is necessary to properly display the date and time pickers.
This fixes the missing date and time pickers in the out of office settings dialog.
> fixed missing oof date and time picker

- calendar/interface/exchangeEvent/mivExchangeEvent.js
When an all day event is modified to have start/end times
(i.e. no longer being an all day event), the order of the transmitted
properties matters for OWA. So the all day property has to be transmitted
before the start/end times, as otherwise the desired times are not applied.
Closes #286.
> Fix adding times to all day event

- README.md
Financial bounties have been transferred to the correct issue #277 now.
> Update link in the README to the financial bounty
